-- removed plant manager, added EMP_IS_ADMIN, Renamed PRODUCT_PLANT_BRIDGE to PRODUCTION_LINE
-- PK_PRODUCT_PLANT_BRIDGE renamed to PK_PRODUCTION_LINE
-- COMPOSITION table renamed to BLUE_PRINT
-- PK_COMPOSITION renamed to PK_BLUE_PRINT
-- All instances of attributes Should now match the current erd
-- (except for where plant manager hasn't been removed on it, but has been removed here, and PROD_DESCRIPTION isn't misspelled)
--Query 1: Creates Employee table
CREATE TABLE EMPLOYEES (
EMP_ID INT NOT NULL IDENTITY(1,1),
EMP_JOB_TITLE VARCHAR(60) NOT NULL,
EMP_IS_ACTIVE CHAR(1) NOT NULL CHECK (EMP_IS_ACTIVE IN ('Y', 'N')),
EMP_IS_ADMIN CHAR(1) NOT NULL CHECK (EMP_IS_ADMIN IN ('Y', 'N')),
EMP_FIRST_NAME VARCHAR(64) NOT NULL, --longer character limit ensures international compliance
EMP_MIDDLE_INITIAL CHAR(1),
EMP_LAST_NAME VARCHAR(64) NOT NULL, --longer character limit ensures international compliance
EMP_SALARY DECIMAL(9,2) NOT NULL, --add size and decimal constraint (default is (10,0))
EMP_DOB DATE NOT NULL,
EMP_USERNAME VARCHAR(30) NOT NULL,
EMP_PASSWORD VARCHAR(100), --This one is nullable so employees can make their password
PLANT_ID INT, --This one is nullable because higher-level employees do not have an assigned plant
EMP_TOKEN VARCHAR(255), --This one is nullable because a token is generated and discarded for every user login
PRIMARY KEY (EMP_ID) --primary key constraint was fine, I prefer to have keys listed below however
);
--Query 2: Creates Plant table
CREATE TABLE PLANT (
PLANT_ID INT NOT NULL IDENTITY(1,1),
PLANT_NATION CHAR(2) NOT NULL, --instead of storing an entire country name, a two-character country code would save space
PLANT_CITY VARCHAR(40) NOT NULL,
PLANT_ZIP CHAR(5) NOT NULL, --using a char datatype enforces a required length, int is not needed since no math would need to be done on a zip code. This also allows zip codes starting with 0 to exist in the database
PLANT_STREET VARCHAR(80) NOT NULL,
PLANT_NAME VARCHAR(40) NOT NULL,
PLANT_STATUS CHAR(1) NOT NULL CHECK (PLANT_STATUS IN ('Y', 'N')), --Same as above, since no math is done on the values, using a char with "Y" and "N" constraints would save space. (maybe change name to PLANT_ACTIVE)
PRIMARY KEY (PLANT_ID), --primary key constraint was fine, I prefer to have keys listed below however
);
--Query 3: Defines foreign key between Plant and Employee
ALTER TABLE EMPLOYEES
ADD FOREIGN KEY(PLANT_ID) REFERENCES PLANT(PLANT_ID);
--Query 4: Creates Vendor table
CREATE TABLE VENDOR (
VEND_ID INT NOT NULL IDENTITY(1,1),
VEND_NAME VARCHAR(100) NOT NULL,
VEND_SPECIALIZATION VARCHAR(255) NOT NULL,
VEND_HQ_NATION CHAR(2) NOT NULL, --instead of storing an entire country name, a two-character country code would save space
VEND_HQ_CITY VARCHAR(40) NOT NULL,
VEND_HQ_ZIP CHAR(5) NOT NULL, --using a char datatype enforces a required length, int is not needed since no math would need to be done on a zip code. This also allows zip codes starting with 0 to exist in the database
VEND_HQ_STREET VARCHAR(100) NOT NULL,
PRIMARY KEY (VEND_ID) --primary key constraint was fine, I prefer to have keys listed below however
);
--Query 5: Creates Components table
CREATE TABLE COMPONENTS (
COMP_ID INT NOT NULL IDENTITY(1,1),
COMP_NAME VARCHAR(255) NOT NULL,
COMP_DESCRIPTION VARCHAR(255) NOT NULL,
COMP_MIN_QUANT INT NOT NULL,
COMP_COST DECIMAL(8,2) NOT NULL, --add size and decimal constraint (default is (10,0))
VEND_ID INT NOT NULL,
PRIMARY KEY (COMP_ID), --primary key constraint was fine, I prefer to have keys listed below however
FOREIGN KEY (VEND_ID) REFERENCES VENDOR(VEND_ID) --replaces query 9
);
--Query 6: Creates Composition table as BLUE_PRINT
CREATE TABLE BLUE_PRINT (
PROD_ID INT NOT NULL,
COMP_ID INT NOT NULL,
COMP_AMOUNT INT NOT NULL,
FOREIGN KEY (COMP_ID) REFERENCES COMPONENTS(COMP_ID), --Replaces query 11
CONSTRAINT PK_BLUE_PRINT PRIMARY KEY ( PROD_ID, COMP_ID)
);
--Query 7: Creates Product table
CREATE TABLE PRODUCT (
PROD_ID INT NOT NULL IDENTITY(1,1),
PROD_NAME VARCHAR(255) NOT NULL,
PROD_DESCRIPTION VARCHAR(255) NOT NULL,
PROD_PRICE DECIMAL(8,2) NOT NULL, --add size and decimal constraint (default is (10,0))
PROD_PRODUCED CHAR(1) NOT NULL CHECK (PROD_PRODUCED IN ('Y', 'N')),
PRIMARY KEY (PROD_ID) --primary key constraint was fine, I prefer to have keys listed below however
);
--Query 8: Defines foreign key between product and BLUE_PRINT
ALTER TABLE BLUE_PRINT
ADD FOREIGN KEY (PROD_ID) REFERENCES PRODUCT(PROD_ID); --Replaces query 11
--Query 9: Creates Product_Plant_Bridge as PRODUCTION_LINE table
CREATE TABLE PRODUCTION_LINE (
PLANT_ID INT NOT NULL,
PROD_ID INT NOT NULL,
PROD_QUANT INT NOT NULL,
PROD_MIN INT NOT NULL,
CONSTRAINT PK_PRODUCTION_LINE PRIMARY KEY (PLANT_ID, PROD_ID),
FOREIGN KEY (PLANT_ID) REFERENCES PLANT(PLANT_ID), --replaces query 12
FOREIGN KEY (PROD_ID) REFERENCES PRODUCT(PROD_ID) --replaces query 12
);
INSERT INTO PLANT (PLANT_NATION, PLANT_CITY, PLANT_ZIP, PLANT_STREET, PLANT_NAME, PLANT_STATUS)
VALUES
('US', 'NEW YORK', '10021', '417 WEST MAIN STREET', 'WEST HOUSE PRODUCTION FACILITY', 'Y'),
('US', 'HOUSTON', '77010', '1319 LOGAN AVENUE', 'HOUSTON TECH PRODUCTIONS', 'Y'),
('US', 'SAN FRANCISCO', '94102', '774 UNDERSIDE WAY', 'CALIFORNIA COMPONENTS FACILITY', 'Y'),
('US', 'SEATTLE', '98039', '1428 SOUTH MILE ROAD', 'NW COMPONENTS PLANT', 'Y'),
('UK', 'MANCHESTER', 'M11AD', '127 NEW CATHEDRAL STREET', 'CENTRAL MANCHESTER PRODUCTION PLANT', 'Y');
INSERT INTO EMPLOYEES (EMP_JOB_TITLE, EMP_IS_ACTIVE, EMP_IS_ADMIN, EMP_FIRST_NAME, EMP_MIDDLE_INITIAL, EMP_LAST_NAME, EMP_SALARY, EMP_DOB, EMP_USERNAME, EMP_PASSWORD, PLANT_ID, EMP_TOKEN)
VALUES
('CEO', 'Y', 'Y', 'BILL', 'T', 'CONWAY', 250000.00, '1982-03-26', 'bconway20', NULL, NULL, NULL),
('PRODUCTION LINE', 'Y', 'N', 'SANDRA', 'J', 'POWELL', 65000.00, '1989-09-14', 'spowell56', NULL, 1, NULL),
('PRODUCTION LINE', 'Y', 'N', 'ALEXANDER', 'W', 'NELSON', 67000.00, '1988-05-26', 'anelson94', NULL, 3, NULL),
('PRODUCTION LINE', 'Y', 'N', 'WILLIAM', 'N', 'BRADLEY', 62000.00, '1995-02-21', 'wbradley77', NULL, 3, NULL),
('CFO', 'Y', 'Y', 'MICHAEL', 'P', 'SMITH', 172000.00, '1983-11-23', 'msmith73', NULL, NULL, NULL);
INSERT INTO VENDOR (VEND_NAME, VEND_SPECIALIZATION, VEND_HQ_NATION, VEND_HQ_CITY, VEND_HQ_ZIP, VEND_HQ_STREET)
VALUES
('SAMSUNG', 'CONSUMER ELECTRONICS AND MICROCHIPS', 'US', 'ENGLEWOOD CLIFFS', '07632', '700 SYLVAN AVENUE'),
('MICRON', 'SEMICONDUCTORS, COMPUTER MEMORY AND DATA', 'US', 'BOISE', '83716', '8000 S FEDERAL WAY'),
('NVIDIA', 'HIGH PERFORMANCE GRAPHICAL AND AI PROCESSORS', 'US', 'SANTA CLARA', '95051', '2788 SAN TOMAS EXPRESSWAY'),
('INTEL', 'SEMICONDUCTORS AND GRAPHICS CHIPS', 'US', 'SANTA CLARA', '95054', '2200 MISSION COLLEGE BOULEVARD'),
('AMD', 'HIGH PERFORMANCE COMPUTING AND AI SEMICONDUCTORS', 'US', 'SANTA CLARA', '95054', '2485 AUGUSTINE DRIVE');
INSERT INTO COMPONENTS (COMP_NAME, COMP_DESCRIPTION, COMP_MIN_QUANT, COMP_COST, VEND_ID)
VALUES
('VOLTAGE REGULATOR MODULE', 'POWER REGULATORS USED TO MANAGE POWER DELIVERY TO SENSITIVE PARTS', 20, 149.99, 2),
('CHIPSET', 'HIGH PERFORMANCE PROCESSING UNITS FOR DEIDICATED SYSTEMS', 10, 267.99, 4),
('GRAPHICAL PROCESSOR', 'HIGH PERFORMANCE GRAPHICS PROCESSOR USED IN PRODUCTION AND AI', 5, 2499.99, 3),
('SEMICONDUCTOR', 'ELECTRIC INSULATOR AND CONDUCTOR FOR POWER DELIVERY', 30, 67.99, 5),
('MICROCHIP', 'SMALLEST LEVEL PROCESSING UNIT', 25, 116.99, 1);
INSERT INTO PRODUCT (PROD_NAME, PROD_DESCRIPTION, PROD_PRICE, PROD_PRODUCED)
VALUES
('PROCESSING UNIT', 'HIGH PERFORMANCE COMPUTER PROCESSING UNIT', 439.99, 'Y'),
('GRAHICAL PROCESSING UNIT', 'HIGH PERFORMANCE GRAPHICS AND AI PROCESSING', 2499.99, 'Y'),
('MEMORY MODULE', 'HIGH SPEED AND CAPACITY MEMORY UNIT', 224.99, 'Y'),
('STORAGE DRIVE', 'HIGH CAPACITY STORAGE DEVICE WITH FAST READ/WRITE SPEEDS', 264.99, 'Y'),
('POWER DELIVERY UNIT', 'EFFICIENT POWER DELIVERY WITH HIGH WATTAGE', 189.99, 'Y');
INSERT INTO BLUE_PRINT (PROD_ID, COMP_ID, COMP_AMOUNT)
VALUES
(1, 5, 15),
(1, 4, 5),
(2, 3, 10),
(2, 5, 25),
(3, 5, 10);
INSERT INTO PRODUCTION_LINE (PLANT_ID, PROD_ID, PROD_QUANT, PROD_MIN)
VALUES
(1, 2, 10, 5),
(3, 1, 18, 10),
(2, 2, 14, 5),
(5, 3, 26, 15),
(4, 1, 12, 10);
